name: core
description: A module that contains all the business logic of the project in Dart.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  hive: ^2.2.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
  mocktail: ^1.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
